# Generated by Django 5.1.1 on 2024-10-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('1st', 'First Type'), ('2nd', 'Second Type'), ('3rd', 'Third Type')], default='1st', max_length=20)),
                ('exceptional', models.BooleanField()),
            ],
        ),
    ]
